### ISSUE TITLE
Plugins do not install when using a PVC for plugins mounted on /plugins-storage

### ISSUE THREAD

**Issue by martinsarrionandia** [traefik/traefik-helm-chart#1261]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v33.0.0

### What version of Traefik are you using?

traefik:v3.2.0

### What did you do?

Install traefik using the helm command line 

```bash
helm repo add traefik https://traefik.github.io/charts
helm repo update

# Install Traefik v3

export TRAEFIK_PLUGINS_PATH=/mnt/traefik-plugins
mkdir $TRAEFIK_PLUGINS_PATH
chown 65532:65532 $TRAEFIK_PLUGINS_PATH
chmod 700 $TRAEFIK_PLUGINS_PATH
semanage fcontext -a -t container_file_t -r s0 $TRAEFIK_PLUGINS_PATH

kubectl create namespace traefik

cat > /root/traefik-volume.yaml << EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-plugins
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  local:
    path: $TRAEFIK_PLUGINS_PATH
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "${acme-domain}"
EOF

kubectl apply -f /root/traefik-volume.yaml

cat > /root/traefik-pvc.yaml << EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: traefik
  name: traefik-plugins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeName: traefik-plugins
EOF

kubectl apply -f /root/traefik-pvc.yaml

helm install --replace traefik traefik/traefik \
  --namespace traefik \
  --set-json deployment.additionalVolumes='[{"name": "plugins","persistentVolumeClaim": {"claimName": "traefik-plugins"}}]' \
  --set-json additionalVolumeMounts='[{"name": "plugins","mountPath": "/plugins-storage"}]' \
  --set providers.kubernetesCRD.enabled=true \
  --set securityContext.seccompProfile.type=RuntimeDefault \
  --set-json service.spec='{"externalTrafficPolicy":"Local"}'
```

Then apply a HelmChartConfig using a terrafrom template.

```yaml
apiVersion: helm.cattle.io/v1

kind: HelmChartConfig
metadata:
  name: traefik
  namespace: traefik
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        enabled: true
    logs:
      general:
        level: "${traefik-log-level}"
      access:
        enabled: "${traefik-access-log}"
    service:
      spec:
        externalTrafficPolicy: "${traefik-external-access-policy}"
    experimental:
      plugins:
        rewrite-body:
          moduleName: "github.com/packruler/rewrite-body"
          version: "v1.2.0"
      crowdsec-bouncer-traefik-plugin:
        moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
        version: "v1.3.5"
```

No plugins are installed. The /plugins-storage is emplty but clearly writable.

```bash
/plugins-storage $ ls -la
total 0
drwx------    2 65532    65532            6 Nov 24 13:20 .
drwxr-xr-x    1 root     root            63 Nov 24 11:40 ..
/plugins-storage $ touch myself
/plugins-storage $ ls -la
total 0
drwx------    2 65532    65532           20 Nov 24 14:00 .
drwxr-xr-x    1 root     root            63 Nov 24 11:40 ..
-rw-r--r--    1 65532    65532            0 Nov 24 14:00 myself
/plugins-storage $ 
```

This works perfectly well with the default emptyDir for the plugins volume.

### What did you see instead?

No plugins are active or installed.

### What is your environment & configuration?

K3S and Rancher (latest) on Centos 9

### Additional Information

```shell

```

**Comment by mloiseleur** [comment]
Hello @martinsarrionandia ,

This issue has already been detected and fixed with PR #1250.

It's part of current rc: v33.1.0-rc1.

There is a complete example on how to do it [here](https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#using-plugins).

Can you confirm that with this version it works as expected ?

**Comment by martinsarrionandia** [comment]
I can confirm that this release candidate fixes https://github.com/traefik/traefik-helm-chart/issues/1261

```bash
cat > /root/traefik-plugins.yaml << EOF
experimental:
  plugins:
    rewrite-body:
      moduleName: "github.com/packruler/rewrite-body"
      version: "v1.2.0"
    crowdsec-bouncer-traefik-plugin:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.3.5"
EOF

helm install traefik traefik/traefik \
  --version 33.1.0-rc1 \
  --namespace traefik \
  --set-json deployment.additionalVolumes='[{"name": "plugins","persistentVolumeClaim": {"claimName": "traefik-plugins"}}]' \
  --set-json additionalVolumeMounts='[{"name": "plugins","mountPath": "/plugins-storage"}]' \
  --set providers.kubernetesCRD.enabled=true \
  --set securityContext.seccompProfile.type=RuntimeDefault \
  --set-json service.spec='{"externalTrafficPolicy":"Local"}' \
  --values /root/traefik-plugins.yaml
```

Here are the pod startup logs. Looks good!

```
Container: traefik
Filter
Connected
2024-11-26T21:08:43Z INF Traefik version 3.2.1 built on 2024-11-20T17:39:47Z version=3.2.1
2024-11-26T21:08:43Z INF Stats collection is enabled.
2024-11-26T21:08:43Z INF Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration.
2024-11-26T21:08:43Z INF Help us improve Traefik by leaving this feature on :)
2024-11-26T21:08:43Z INF More details on: https://doc.traefik.io/traefik/contributing/data-collection/
2024-11-26T21:08:43Z INF Loading plugins... plugins=["crowdsec-bouncer-traefik-plugin","rewrite-body"]
2024-11-26T21:08:44Z INF Plugins loaded. plugins=["crowdsec-bouncer-traefik-plugin","rewrite-body"]
```

Plugins are stored correctly.

```bash
~ $ cd /plugins-storage/
/plugins-storage $ ls -la
total 0
drwx------    4 65532    65532           37 Nov 26 21:08 .
drwxr-xr-x    1 root     root            63 Nov 26 21:08 ..
drwxr-xr-x    3 65532    65532           42 Nov 26 21:08 archives
drwxr-xr-x    3 65532    65532           28 Nov 26 21:08 sources
/plugins-storage $ 
```

This is after a reboot

```
Container: traefik
Filter
Connected
2024-11-26T21:17:14Z INF Traefik version 3.2.1 built on 2024-11-20T17:39:47Z version=3.2.1
2024-11-26T21:17:14Z INF Stats collection is enabled.
2024-11-26T21:17:14Z INF Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration.
2024-11-26T21:17:14Z INF Help us improve Traefik by leaving this feature on :)
2024-11-26T21:17:14Z INF More details on: https://doc.traefik.io/traefik/contributing/data-collection/
2024-11-26T21:17:14Z INF Loading plugins... plugins=["rewrite-body","crowdsec-bouncer-traefik-plugin"]
2024-11-26T21:17:24Z ERR Request failed error={"Err":{},"Op":"Get","URL":"https://plugins.traefik.io/public/download/github.com/packruler/rewrite-body/v1.2.0"} method=GET url=https://plugins.traefik.io/public/download/github.com/packruler/rewrite-body/v1.2.0
2024-11-26T21:17:25Z INF Plugins loaded. plugins=["rewrite-body","crowdsec-bouncer-traefik-plugin"]
```

**Comment by martinsarrionandia** [comment]
hello @mloiseleur 

Traefik 33.1-rc1 does not fix the issue I reported. 

It does however fix #1261 from what I can tell.

**Comment by mloiseleur** [comment]
> Traefik 33.1-rc1 does not fix the issue I reported.

Gotcha.
 
> It does however fix [#1261](https://github.com/traefik/traefik-helm-chart/issues/1261) from what I can tell.

The issue you reported _is_ #1261. So I'm not sure to follow 🤔 , does this mean this issue can be closed and you will open a new one about another issue ?

**Comment by martinsarrionandia** [comment]
#1261 This issue will not let you install traefik due to duplicate volume creation. This only happens whens you specify a PVC and plugins during the install.

My issue is different. I am installing traefik with a PVC for plugins without installing any plugins. Then later on I am installing the plugins via a HelmChartConfig resources. No plugins are installed. However the PVC exists and is writable. This method works using the default emptyDir{}

Thanks!

**Comment by mloiseleur** [comment]
This reboot issue is linked to how the CI/CD is configured on your infrastructure. 
The expected resources (ie: YAML) are produced by this Chart, so I close this issue.
Feel free to open a new issue if there is something on the Chart (reproducible with helm template, for instance).

The [community forum] (https://community.traefik.io/)  might have examples of how other users addressed the challenge you are facing with your CI/CD. It is pretty active, so you might find that your question has already been answered there.

**Comment by martinsarrionandia** [comment]
@mloiseleur Thank you for the explanation. I now fully understand the problem;

HelmChartConfig resources only work on Helm resources installed by K3S during setup. 

Thank you!!
