### ISSUE TITLE
Aggregate CRD access to default user-facing roles

### ISSUE THREAD

**Issue by AndreKR** [traefik/traefik-helm-chart#461]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'm *relatively* new to Kubernetes, so there might be a good reason not to do this, but let me describe my experience.

In a deploy script I'm creating an Ingress with a path and I'd like to strip that path. In Traefik 1.7 I used `PathPrefixStrip`, but I'm migrating to Traefik 2.4. So in my deploy script I tried to create a StripPrefix Middleware for the respective path currently being deployed.

I got an error:

```
User "system:serviceaccount:deploy-413:deploy-413-service-account" cannot get resource "middlewares" in API group "traefik.containo.us" in the namespace "deploy-413"
```

My deploy job is running with Kubernetes' [default `admin` role](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles).

I was curious why I can for example create [cert-manager](https://cert-manager.io/) CRDs but not Traefik CRD. It turns out that the cert-manager Helm chart creates [a ClusterRole](https://github.com/jetstack/cert-manager/blob/1b7e706c72655b9244fa547c3029d89ee9cb01e2/deploy/charts/cert-manager/templates/rbac.yaml#L434-L452) that has `rbac.authorization.k8s.io/aggregate-to-admin: "true"` set.

I think the Traefik Helm chart should set `rbac.authorization.k8s.io/aggregate-to-admin: "true"` on the ClusterRoles to make sure that [predefined admins](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles) can automatically create resources like Middleware.

**Comment by faust64** [comment]
Hi,

You're right. Someone that has `admin` (or even `edit`) privileges within a Namespace should be able to configure his Middlewares, and other Traefik related objects, as much as they can operate their own Ingresses.

The current ClusterRole grants privileges to patch/update ingress, gateways, gatewayclasses and httproutes statuses. While as you've seen: it would only allow the Traefik Ingress Controller to get/list/watch Traefik Custom Resources.

We may want to add another ClusterRole ... If you're up for it, feel free to submit a PR. Otherwise I'll look into it.

**Comment by mloiseleur** [comment]
Hello @AndreKR,

I updated PR #464 from  @faust64 and extended it with some tests and capacity to enable `admin`, `edit` or `view`. 

Will it solve your issue ?

**Comment by powo** [comment]
Users with `ClusterRole/admin` still cannot **manage** (create/delete/update...) Traefik Resources within their namespace.

 The merged PR #644 allows them only to readl/list/watch the Resources.
 
 The `traefik-aggregate` ClusterRole proposed in #464 would have allowed this, but it has been closed in favour of #644.

**Comment by faust64** [comment]
#664 looks good

However, that clusterrole grants privileges to traefik controller posting/updating resource status (eg tcproutes/status).
Arguably, this is not some privilege you would want to delegate end-users. Only controller (and cluster admins) should have those permissions.

Besides, if the purpose is to grant someone with local-admin or local-edit rolebinding, privileges to operate their own Traefik resources: it would make more sense to have ClusterRoles focusing on those objects.
While controller requires read access to secrets, services, endpoints, ... as a cluster admin, should I want to grant my end-users with management privileges over their own Traefik custom resources: I do not necessarily want them being able to see secrets (or if I do, this would go through some specific aggregated clusterrole and/or rolebinding). Simliarily, if PSP enabled, I certainly don't want to grant anyone with their admin rolebinding usage of that traefik PSP.

**Comment by jim-barber-he** [comment]
I notice this is closed, but this still seems to be a problem?
There is only one ClusterRole, and you can set `rbac.aggregateTo:` to `[admin]` and it adds the `rbac.authorization.k8s.io/aggregate-to-admin: "true"` label to it as expected.
However the role itself still only has read-only access to the CRDs, there are no rules to allow managing the CRDs as far as I can tell?

**Comment by mloiseleur** [comment]
@jim-barber-he There is a WIP to put CRD in a dedicated chart, see https://github.com/traefik/traefik-helm-chart/pull/1223 . 

Feel free to open an issue or a PR if something is missing.

**Comment by jim-barber-he** [comment]
Ok. That chart just seems to be handling the CRDs and not the ClusterRoles? Which chart would need the change?

Currently I've hacked up my own local changes to install cluster roles like so (helm output)
```diff
traefik, traefik:edit, ClusterRole (rbac.authorization.k8s.io) has been added:
- 
+ # Source: additions/templates/clusterrole.yaml
+ apiVersion: rbac.authorization.k8s.io/v1
+ kind: ClusterRole
+ metadata:
+   labels:
+     rbac.authorization.k8s.io/aggregate-to-admin: "true"
+     rbac.authorization.k8s.io/aggregate-to-edit: "true"
+   name: traefik:edit
+ rules:
+   - apiGroups:
+     - traefik.io
+     resources:
+     - ingressroutes
+     - ingressroutetcps
+     - ingressrouteudps
+     - middlewares
+     - middlewaretcps
+     - serverstransports
+     - serverstransporttcps
+     - tlsoptions
+     - tlsstores
+     - traefikservices
+     verbs:
+     - create
+     - delete
+     - patch
+     - update
traefik, traefik:view, ClusterRole (rbac.authorization.k8s.io) has been added:
- 
+ # Source: additions/templates/clusterrole.yaml
+ apiVersion: rbac.authorization.k8s.io/v1
+ kind: ClusterRole
+ metadata:
+   labels:
+     rbac.authorization.k8s.io/aggregate-to-admin: "true"
+     rbac.authorization.k8s.io/aggregate-to-edit: "true"
+     rbac.authorization.k8s.io/aggregate-to-view: "true"
+   name: traefik:view
+ rules:
+   - apiGroups:
+     - traefik.io
+     resources:
+     - ingressroutes
+     - ingressroutetcps
+     - ingressrouteudps
+     - middlewares
+     - middlewaretcps
+     - serverstransports
+     - serverstransporttcps
+     - tlsoptions
+     - tlsstores
+     - traefikservices
+     verbs:
+     - get
+     - list
+     - watch
```
Ideally whatever chart creates the cluster roles would do something similar.

**Comment by natcl** [comment]
We've been facing the same issue and were wondering why this issue was closed ? Seems strange that we need to manage these manually...

Thanks !

**Comment by mloiseleur** [comment]
@natcl the feature has been implemented with https://github.com/traefik/traefik-helm-chart/pull/664/

Feel free to open a new issue or a PR if something is missing.
